### ISSUE TITLE
[FIX] 회원탈퇴 후 앱 재시동 안하고 재가입시 LinkView 미노출

### ISSUE THREAD

**Issue by RubiksCube33** [Dr-Yomang/Yomang#101]
# Description
회원탈퇴를 하고
앱을 끄지 않은 상태에서 재가입을 하면
멀쩡하게 재가입이 되긴 하는데, LinkView가 노출되지 않습니다.

# TODO
- [x] 원인파악하기
- [ ] 회원탈퇴 후 재가입 시 LinkView 노출되게 수정

**Comment by dayo2n** [comment]
resolve in #111
